# SD212: Graph mining

# Sparse matrices

The objective of this lab is to learn to work with sparse matrices.

In [1]:
import numpy as np
from scipy import sparse

## CSR format

We first focus on the [CSR](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html)  (Compressed Sparse Row) format. Note that there is the [CSC](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.html) (Compressed Sparse Column) format, which is nothing but the CSR format of the transpose matrix.

In [2]:
# random matrix (dense format)
X_dense = np.random.randint(3, size = (10,5))

In [3]:
X_dense

array([[1, 1, 0, 1, 2],
       [2, 1, 1, 0, 0],
       [1, 1, 0, 1, 2],
       [2, 1, 2, 1, 0],
       [1, 0, 0, 1, 1],
       [2, 2, 1, 1, 1],
       [1, 1, 1, 0, 1],
       [1, 0, 2, 2, 2],
       [2, 2, 0, 0, 0],
       [0, 1, 1, 0, 2]])

In [4]:
X_csr = sparse.csr_matrix(X_dense)

In [5]:
X_csr.shape

(10, 5)

In [6]:
X_csr.nnz

36

The data structure consists of 3 vectors:

In [7]:
X_csr.indices

array([0, 1, 3, 4, 0, 1, 2, 0, 1, 3, 4, 0, 1, 2, 3, 0, 3, 4, 0, 1, 2, 3,
       4, 0, 1, 2, 4, 0, 2, 3, 4, 0, 1, 1, 2, 4])

In [8]:
X_csr.indptr

array([ 0,  4,  7, 11, 15, 18, 23, 27, 31, 33, 36])

In [9]:
X_csr.data

array([1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 2], dtype=int32)

## To do

Can you find the number of non-zeros ``nnz`` and the shape of the matrix from these vectors?

The number of non zeros are the last element of X_csr.indptr or the number of elements in X_csr.indices, X_csr.data.
The number of rows equal the n

In [42]:
nnz = X_csr.indptr[-1]
nnz

36

In [45]:
nnz = X_csr.indices.shape[0]
nnz

36

In [46]:
nnz = X_csr.data.shape[0]
nnz

36

In [47]:
n_rows = X_csr.indptr.shape[0] - 1
n_cols = X_csr.indices.max() + 1
n_rows, n_cols

(10, 5)

## Arithmetic

Usual arithmetic operations apply to sparse matrices. The only contraint is to have the sparse matrix on the left-hand side of the operator.

In [48]:
n_row, n_col = 10, 4
X_dense = np.random.randint(2, size = (n_row, n_col))
X = sparse.csr_matrix(X_dense)

In [49]:
X_dense

array([[1, 1, 0, 0],
       [1, 1, 1, 1],
       [1, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 1, 0]])

In [50]:
a = np.ones(n_col, dtype=int)

In [51]:
b = X.dot(a)

In [52]:
b

array([2, 4, 2, 1, 1, 3, 2, 1, 1, 2], dtype=int32)

In [53]:
a = np.ones(n_row, dtype=int)
b = X.T.dot(a)

In [54]:
b

array([5, 4, 7, 3], dtype=int32)

In [55]:
A = np.random.randint(2, size=(n_col, 2))
B = X.dot(A)

In [57]:
A

array([[1, 1],
       [1, 0],
       [0, 0],
       [0, 0]])

In [58]:
B

array([[2, 1],
       [2, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [1, 0]], dtype=int32)

In [59]:
A = sparse.csr_matrix(A)
B = X.dot(A)

In [60]:
B

<10x2 sparse matrix of type '<class 'numpy.intc'>'
	with 12 stored elements in Compressed Sparse Row format>

In [61]:
B.toarray()

array([[2, 1],
       [2, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [1, 0]], dtype=int32)

In [62]:
X.T.dot(X)

<4x4 sparse matrix of type '<class 'numpy.intc'>'
	with 16 stored elements in Compressed Sparse Column format>

In [63]:
X.dot(X.T)

<10x10 sparse matrix of type '<class 'numpy.intc'>'
	with 74 stored elements in Compressed Sparse Row format>

In [64]:
n_row, n_col = 10, 5
X_dense = np.random.randint(3, size = (n_row, n_col))
X = sparse.csr_matrix(X_dense)

In [66]:
Y = X > 1

In [67]:
Y

<10x5 sparse matrix of type '<class 'numpy.bool_'>'
	with 16 stored elements in Compressed Sparse Row format>

In [68]:
Y.dot(np.ones(n_col, dtype=int))

array([2, 1, 3, 1, 0, 2, 1, 1, 2, 3], dtype=int32)

In [69]:
Y.dot(np.ones(n_col, dtype=bool))

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True])

In [70]:
Z = 2 * X + 5 * Y

In [71]:
Z

<10x5 sparse matrix of type '<class 'numpy.intc'>'
	with 33 stored elements in Compressed Sparse Row format>

## To do

Consider the following matrix:

In [85]:
n_row, n_col = 20, 4
X = sparse.csr_matrix(np.random.randint(3, size = (n_row, n_col)))

* Compute the vector of the Euclidean norm of each row.

In [90]:
X.data

array([2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 2, 1, 1,
       2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 2, 2, 1, 2,
       2, 1, 2, 1, 1, 1], dtype=int32)

In [105]:
X2 = X.data **2
X2

array([4, 1, 1, 1, 1, 4, 1, 1, 4, 4, 4, 4, 1, 4, 4, 4, 4, 1, 1, 4, 1, 1,
       4, 1, 4, 4, 4, 1, 4, 1, 1, 1, 4, 1, 1, 4, 1, 1, 1, 4, 4, 4, 1, 4,
       4, 1, 4, 1, 1, 1], dtype=int32)

In [103]:
X2 = np.concatenate((X2, np.zeros(1)))

In [93]:
X.indptr

array([ 0,  3,  5,  7,  8, 10, 12, 15, 16, 19, 23, 27, 30, 31, 33, 35, 38,
       42, 44, 48, 50])

In [106]:
norm = np.zeros(n_row)
for i in range(n_row):
    norm[i] = np.sqrt(np.sum(X2[X.indptr[i]:X.indptr[i+1]]))
    
norm

array([2.44948974, 1.41421356, 2.23606798, 1.        , 2.82842712,
       2.82842712, 3.        , 2.        , 2.44948974, 3.16227766,
       3.60555128, 2.44948974, 1.        , 2.23606798, 1.41421356,
       2.44948974, 3.60555128, 2.23606798, 3.16227766, 1.41421356])

## Slicing

Sparse matrices can be sliced like numpy arrays.

In [78]:
n_row, n_col = 10, 5
X_dense = np.random.randint(3, size = (n_row, n_col))

In [79]:
X = sparse.csr_matrix(X_dense)

In [80]:
indices = [2, 5, 6]

In [81]:
X[indices]

<3x5 sparse matrix of type '<class 'numpy.intc'>'
	with 8 stored elements in Compressed Sparse Row format>

In [82]:
X[:, [1, 3]]

<10x2 sparse matrix of type '<class 'numpy.intc'>'
	with 9 stored elements in Compressed Sparse Row format>

## To do 

Consider the following matrix:

In [110]:
n_row, n_col = 20, 10
X = sparse.csr_matrix(np.random.randint(3, size = (n_row, n_col)))

* Select the 5 rows of largest sums and build the corresponding CSR matrix (size 5 x 10).

In [115]:
X.indptr

array([  0,   7,  16,  24,  31,  36,  41,  48,  53,  59,  65,  71,  76,
        82,  90,  97, 105, 114, 122, 127, 134])

In [117]:
X.indices

array([1, 2, 3, 5, 6, 8, 9, 0, 1, 2, 3, 4, 5, 7, 8, 9, 1, 2, 3, 5, 6, 7,
       8, 9, 0, 1, 3, 4, 5, 6, 8, 0, 3, 5, 7, 9, 0, 1, 6, 8, 9, 1, 4, 5,
       6, 7, 8, 9, 0, 1, 2, 3, 7, 0, 1, 2, 3, 7, 8, 1, 3, 4, 5, 6, 7, 1,
       3, 4, 5, 6, 9, 2, 3, 5, 8, 9, 0, 4, 6, 7, 8, 9, 0, 1, 2, 4, 5, 6,
       7, 8, 0, 2, 3, 4, 5, 7, 8, 0, 1, 2, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4,
       5, 7, 8, 9, 0, 1, 3, 5, 6, 7, 8, 9, 1, 2, 6, 7, 9, 2, 4, 5, 6, 7,
       8, 9])

In [142]:
sum_row_X = np.sum(X, axis=1).flatten()

In [143]:
sum_row_X.shape

(1, 20)

In [156]:
max_row_id = np.argsort(sum_row_X)
max_row_id

matrix([[11,  5,  7, 12,  8,  0,  4, 14, 18,  9,  6, 19, 10, 17,  3,  2,
         13, 15,  1, 16]], dtype=int64)

In [165]:
five_largest_row = np.sort(max_row_id[0, :5])
five_largest_row[]

matrix([[ 5,  7,  8, 11, 12]], dtype=int64)

In [168]:
five_largest_row[0]

matrix([[ 5,  7,  8, 11, 12]], dtype=int64)

In [169]:
five_largest_row[0,1]

7

In [170]:
Y_data = []
Y_indptr = np.zeros(1)
Y_indices = []
for i in range(5):
    row = five_largest_row[0, i]
    Y_data = np.concatenate((Y_data, X.data[X.indptr[row]: X.indptr[row+1]]))
    
    nnz = X.indptr[row+1] - X.indptr[row]
    Y_indptr = np.append(Y_indptr, Y_indptr[-1] + nnz)
    Y_indices = np.append(Y_indices, X.indices[X.indptr[row]: X.indptr[row+1]])

In [171]:
Y_data

array([1., 1., 1., 2., 2., 2., 1., 2., 1., 1., 2., 1., 1., 1., 1., 2., 1.,
       1., 2., 1., 2., 1., 1., 1., 2., 2., 1.])

In [172]:
Y_indptr

array([ 0.,  5., 10., 16., 21., 27.])

In [173]:
Y_indices

array([0., 1., 6., 8., 9., 0., 1., 2., 3., 7., 0., 1., 2., 3., 7., 8., 2.,
       3., 5., 8., 9., 0., 4., 6., 7., 8., 9.])

## DIAG format

In [174]:
D = sparse.diags(np.arange(10))

In [175]:
D

<10x10 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements (1 diagonals) in DIAgonal format>

In [176]:
D.data

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [177]:
D.nnz

10

In [178]:
D = sparse.csr_matrix(D)

In [179]:
D.data

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [180]:
D.nnz

9

In [186]:
D

<4x4 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements (1 diagonals) in DIAgonal format>

In [181]:
n_row, n_col = 10, 4
X = sparse.csr_matrix(np.random.randint(2, size = (n_row, n_col)))

In [182]:
D.dot(X)

<10x4 sparse matrix of type '<class 'numpy.float64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [183]:
D = sparse.diags(np.ones(4))

In [184]:
X.dot(D)

<10x4 sparse matrix of type '<class 'numpy.float64'>'
	with 19 stored elements in Compressed Sparse Row format>

## To do

Consider the following matrix:

In [187]:
n_row, n_col = 20, 4
X = sparse.csr_matrix(np.random.randint(2, size = (n_row, n_col)))

Using sparse diagonal matrices:
* Normalize this matrix so that each row sums to 1 (or to 0 if the whole row is zero). 

In [188]:
X.indptr

array([ 0,  1,  2,  4,  5,  6,  8, 10, 13, 15, 16, 19, 22, 24, 26, 26, 28,
       30, 32, 35, 38])

In [189]:
X.indices

array([2, 2, 0, 1, 1, 1, 0, 1, 0, 3, 0, 2, 3, 0, 2, 2, 0, 2, 3, 0, 1, 2,
       1, 2, 0, 3, 0, 2, 0, 2, 1, 3, 0, 1, 3, 1, 2, 3])

In [190]:
a = np.ones(n_col)
Y = X.dot(a)
Y

array([1., 1., 2., 1., 1., 2., 2., 3., 2., 1., 3., 3., 2., 2., 0., 2., 2.,
       2., 3., 3.])

In [192]:
nnz = []
for i in range(20):
    nnz.append(X.indptr[i+1] - X.indptr[i])

In [196]:
X.data

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [193]:
Z_data = X.data/np.repeat(Y, nnz)

In [194]:
Z_data

array([1.        , 1.        , 0.5       , 0.5       , 1.        ,
       1.        , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.33333333, 0.33333333, 0.33333333, 0.5       , 0.5       ,
       1.        , 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.5       , 0.5       , 0.5       ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.5       , 0.5       , 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333])

## COO format

Another way to represent sparse matrices is the COO (COOrdinate) format. It is useful to load a matrix from a list of entries.

In [197]:
row = [1, 4, 2]
col = [2, 0, 2]
data = [1, 2, 3]

In [198]:
X_coo = sparse.coo_matrix((data, (row, col)), shape=(5, 5))

In [199]:
X_coo

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 3 stored elements in COOrdinate format>

In [200]:
X_coo.row

array([1, 4, 2])

In [201]:
X_coo.col

array([2, 0, 2])

In [202]:
X_coo.data

array([1, 2, 3])

You can change the format:

In [203]:
X_csr = X_coo.tocsr()

In [204]:
X_csr

<5x5 sparse matrix of type '<class 'numpy.intc'>'
	with 3 stored elements in Compressed Sparse Row format>

In [205]:
X_csr.indices

array([2, 2, 0])

In [206]:
X_csr.indptr

array([0, 0, 1, 2, 2, 3])

In [207]:
X_csr.data

array([1, 3, 2], dtype=int32)

In [208]:
X_csr.tocoo()

<5x5 sparse matrix of type '<class 'numpy.intc'>'
	with 3 stored elements in COOrdinate format>

You can directly load a CSR matrix from COO format:

In [209]:
X_csr = sparse.csr_matrix((data, (row, col)), shape=(5, 5))

In [210]:
X_csr

<5x5 sparse matrix of type '<class 'numpy.intc'>'
	with 3 stored elements in Compressed Sparse Row format>

Duplicate entries are summed in CSR, not in COO:

In [211]:
row = [1, 4, 2, 1]
col = [2, 0, 2, 2]
data = [1, 2, 3, 4]

In [212]:
X_coo = sparse.coo_matrix((data, (row, col)), shape=(5, 5))

In [213]:
X_coo

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 4 stored elements in COOrdinate format>

In [214]:
X_coo.data

array([1, 2, 3, 4])

In [215]:
X_csr = sparse.csr_matrix((data, (row, col)), shape=(5, 5))

In [216]:
X_csr

<5x5 sparse matrix of type '<class 'numpy.intc'>'
	with 3 stored elements in Compressed Sparse Row format>

In [217]:
X_csr.data

array([5, 3, 2], dtype=int32)

## To do

* Build the following matrix in sparse CSR format:
$$
\begin{pmatrix}
0 & 0 & 1& 2\\
3 & 0& 0& 0\\
0& 0& 4& 0
\end{pmatrix}
$$

In [218]:
data = [1, 2, 3, 4]
row = [0, 0, 1, 2]
col = [2, 3, 0, 2]
X_csr = sparse.csr_matrix((data, (row, col)))

In [219]:
X_csr

<3x4 sparse matrix of type '<class 'numpy.intc'>'
	with 4 stored elements in Compressed Sparse Row format>